// lib/data/mock_data.dart

import '../models/recipe.dart';
import '../models/ingredient.dart'; 


const List<Recipe> mockRecipes = [

  // --- Main Dishes (Ana Yemekler) 
  Recipe(
    id: 'm1',
    title: 'Classic Lasagna',
    category: 'Main Dish',
    imageUrl: 'assets/images/lasagna.jpg', 
    servingSize: 8,
    cookingTimeMinutes: 45,
    ingredients: const [
      Ingredient(quantity: 1.0, unit: 'lb', name: 'ground beef'),
      Ingredient(quantity: 1.0, unit: 'box', name: 'lasagna noodles'),
      Ingredient(quantity: 15.0, unit: 'oz', name: 'ricotta cheese'),
      Ingredient(quantity: 2.0, unit: 'large', name: 'eggs'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'Parmesan cheese'),
      Ingredient(quantity: 2.0, unit: 'jars', name: 'marinara sauce'),
      Ingredient(quantity: 2.0, unit: 'cups', name: 'shredded mozzarella'),
    ],
    instructions: [
      'Brown the ground beef and drain fat. Stir in marinara sauce.',
      'In a bowl, mix ricotta, eggs, and Parmesan cheese.',
      'Cook lasagna noodles according to package directions.',
      'In a baking dish, layer sauce, noodles, ricotta mixture, and mozzarella.',
      'Repeat layers. Bake at 375°F for 45 minutes.',
    ],
  ),
  Recipe(
    id: 'm2',
    title: 'Spicy Chicken Curry',
    category: 'Main Dish',
    imageUrl: 'assets/images/SpicyChickenCurry.jpg',
    servingSize: 4,
    cookingTimeMinutes: 25,
    ingredients: const [
      Ingredient(quantity: 2.0, unit: '', name: 'chicken breasts, diced'),
      Ingredient(quantity: 1.0, unit: '', name: 'onion, chopped'),
      Ingredient(quantity: 2.0, unit: '', name: 'cloves garlic, minced'),
      Ingredient(quantity: 1.0, unit: 'tbsp', name: 'ginger, grated'),
      Ingredient(quantity: 1.0, unit: 'can', name: 'coconut milk'),
      Ingredient(quantity: 2.0, unit: 'tbsp', name: 'curry paste'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'chicken broth'),
    ],
    instructions: [
      'Sauté onion, garlic, and ginger until soft.',
      'Add chicken and cook until browned.',
      'Stir in curry paste for 1 minute.',
      'Pour in coconut milk and broth. Simmer for 20 minutes.',
      'Serve hot with rice.',
    ],
  ),
  Recipe(
    id: 'm3',
    title: 'Grilled Salmon with Lemon Butter',
    category: 'Main Dish',
    imageUrl: 'assets/images/GrilledSalmonwithLemonButter.jpg',
    servingSize: 4,
    cookingTimeMinutes: 10,
    ingredients: const [
      Ingredient(quantity: 4.0, unit: '', name: 'salmon fillets'),
      Ingredient(quantity: 2.0, unit: 'tbsp', name: 'olive oil'),
      Ingredient(quantity: 0.0, unit: '', name: 'Salt and pepper to taste'),
      Ingredient(quantity: 0.25, unit: 'cup', name: 'butter, melted'),
      Ingredient(quantity: 2.0, unit: 'tbsp', name: 'lemon juice'),
      Ingredient(quantity: 1.0, unit: 'tsp', name: 'garlic powder'),
    ],
    instructions: [
      'Preheat grill to medium-high heat.',
      'Brush salmon with olive oil and season with salt and pepper.',
      'Grill salmon for 4-5 minutes per side.',
      'Mix melted butter, lemon juice, and garlic powder.',
      'Drizzle lemon butter over grilled salmon before serving.',
    ],
  ),
    Recipe(
    id: 'm4',
    title: 'Vegetable Stir Fry',
    category: 'Main Dish',
    imageUrl: 'assets/images/stir_fry.jpg',
    servingSize: 4,
    cookingTimeMinutes: 15,
    ingredients: const [
      Ingredient(quantity: 2.0, unit: 'cups', name: 'broccoli florets'),
      Ingredient(quantity: 1.0, unit: '', name: 'red bell pepper, sliced'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'snap peas'),
      Ingredient(quantity: 2.0, unit: '', name: 'carrots, julienned'),
      Ingredient(quantity: 2.0, unit: 'tbsp', name: 'soy sauce'),
      Ingredient(quantity: 1.0, unit: 'tbsp', name: 'sesame oil'),
      Ingredient(quantity: 2.0, unit: '', name: 'cloves garlic, minced'),
    ],
    instructions: [
      'Heat sesame oil in a large pan over medium-high heat.',
      'Add garlic and sauté for 30 seconds.',
      'Add vegetables and stir fry for 5-7 minutes.',
      'Pour in soy sauce and cook for another 2 minutes.',
      'Serve hot with rice or noodles.',
    ],
  ),
    Recipe(
    id: 'm5',
    title: 'Chicken Alfredo Pasta',
    category: 'Main Dish',
    imageUrl: 'assets/images/alfredo.jpg',
    servingSize: 4,
    cookingTimeMinutes: 20,
    ingredients: const [
      Ingredient(quantity: 2.0, unit: '', name: 'chicken breasts, sliced'),
      Ingredient(quantity: 8.0, unit: 'oz', name: 'fettuccine pasta'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'heavy cream'),
      Ingredient(quantity: 0.5, unit: 'cup', name: 'grated Parmesan cheese'),
      Ingredient(quantity: 2.0, unit: '', name: 'cloves garlic, minced'),
      Ingredient(quantity: 2.0, unit: 'tbsp', name: 'butter'),
    ],
    instructions: [
      'Cook fettuccine according to package directions.',
      'In a pan, melt butter and sauté garlic until fragrant.',
      'Add chicken and cook until no longer pink.',
      'Pour in heavy cream and simmer for 5 minutes.',
      'Stir in Parmesan cheese until sauce thickens. Combine with pasta and serve.',
    ],
  ),
    Recipe(
    id: 'm6',
    title: 'Beef Stroganoff',
    category: 'Main Dish',
    imageUrl: 'assets/images/stroganoff.jpg',

    servingSize: 4,
    cookingTimeMinutes: 20,
    ingredients: const [
      Ingredient(quantity: 1.0, unit: 'lb', name: 'beef sirloin, sliced'),
      Ingredient(quantity: 1.0, unit: '', name: 'onion, chopped'),
      Ingredient(quantity: 8.0, unit: 'oz', name: 'mushrooms, sliced'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'beef broth'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'sour cream'),
      Ingredient(quantity: 2.0, unit: 'tbsp', name: 'flour'),
      Ingredient(quantity: 2.0, unit: 'tbsp', name: 'butter'),
    ],

    instructions: [
      'In a pan, melt butter and sauté onion and mushrooms until soft.',
      'Add beef and cook until browned.',
      'Sprinkle flour over beef and stir to coat.',
      'Pour in beef broth and simmer for 10 minutes.',
      'Stir in sour cream and heat through. Serve over egg noodles.',
    ],
    
    
  ),
  Recipe(
    id: 'm7',
    title: 'Shrimp Scampi',
    category: 'Main Dish',
    imageUrl: 'assets/images/shrimp_scampi.jpg',
    servingSize: 4,
    cookingTimeMinutes: 15,
    ingredients: const [
      Ingredient(quantity: 1.0, unit: 'lb', name: 'shrimp, peeled and deveined'),
      Ingredient(quantity: 4.0, unit: '', name: 'cloves garlic, minced'),
      Ingredient(quantity: 0.25, unit: 'cup', name: 'white wine'),
      Ingredient(quantity: 2.0, unit: 'tbsp', name: 'lemon juice'),
      Ingredient(quantity: 0.25, unit: 'cup', name: 'chopped parsley'),
      Ingredient(quantity: 2.0, unit: 'tbsp', name: 'butter'),
      Ingredient(quantity: 8.0, unit: 'oz', name: 'linguine pasta'),
    ],
    instructions: [
      'Cook linguine according to package directions.',
      'In a pan, melt butter and sauté garlic until fragrant.',
      'Add shrimp and cook until pink.',
      'Pour in white wine and lemon juice, simmer for 2 minutes.',
      'Toss shrimp mixture with cooked linguine and garnish with parsley.',
    ],
  ),
  Recipe(
    id: 'm8',
    title: 'Stuffed Bell Peppers',
    category: 'Main Dish',
    imageUrl: 'assets/images/stuffed_peppers.jpg',
    servingSize: 4,
    cookingTimeMinutes: 30,
    ingredients: const [
      Ingredient(quantity: 4.0, unit: '', name: 'bell peppers, tops cut off and seeds removed'),
      Ingredient(quantity: 1.0, unit: 'lb', name: 'ground turkey'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'cooked rice'),
      Ingredient(quantity: 1.0, unit: 'can', name: 'diced tomatoes'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'shredded cheese'),
      Ingredient(quantity: 1.0, unit: 'tsp', name: 'Italian seasoning'),
    ],
    instructions: [
      'Preheat oven to 375°F.',
      'In a pan, cook ground turkey until browned.',
      'Stir in cooked rice, diced tomatoes, and Italian seasoning.',
      'Stuff bell peppers with turkey mixture and top with cheese.',
      'Bake for 25-30 minutes until peppers are tender and cheese is melted.',
    ],
  ),
   Recipe(
    id: 'm9',
    title: 'Chicken Fajitas',
    category: 'Main Dish',
    imageUrl: 'assets/images/chicken_fajitas.jpg',
    servingSize: 4,
    cookingTimeMinutes: 20,
    ingredients: const [
      Ingredient(quantity: 2.0, unit: '', name: 'chicken breasts, sliced'),
      Ingredient(quantity: 1.0, unit: '', name: 'red bell pepper, sliced'),
      Ingredient(quantity: 1.0, unit: '', name: 'green bell pepper, sliced'),
      Ingredient(quantity: 1.0, unit: '', name: 'onion, sliced'),
      Ingredient(quantity: 2.0, unit: 'tbsp', name: 'fajita seasoning'),
      Ingredient(quantity: 8.0, unit: '', name: 'flour tortillas'),
    ],
    instructions: [
      'In a pan, cook chicken with fajita seasoning until cooked through.',
      'Add bell peppers and onion, sauté until tender.',
      'Warm tortillas in a separate pan.',
      'Serve chicken and vegetables in tortillas with desired toppings.',
    ],
  ), 	
  Recipe(
    id: 'm10',
    title: 'Margherita Pizza',
    category: 'Main Dish',
    imageUrl: 'assets/images/margherita_pizza.jpg',
    servingSize: 4,
    cookingTimeMinutes: 15,
    ingredients: const [
      Ingredient(quantity: 1.0, unit: '', name: 'pizza dough'),
      Ingredient(quantity: 0.5, unit: 'cup', name: 'tomato sauce'),
      Ingredient(quantity: 8.0, unit: 'oz', name: 'fresh mozzarella, sliced'),
      Ingredient(quantity: 0.0, unit: '', name: 'Fresh basil leaves'),
      Ingredient(quantity: 2.0, unit: 'tbsp', name: 'olive oil'),
    ],
    instructions: [
      'Preheat oven to 475°F.',
      'Roll out pizza dough on a baking sheet.',
      'Spread tomato sauce over dough, top with mozzarella slices.',
      'Bake for 10-12 minutes until crust is golden and cheese is bubbly.',
      'Garnish with fresh basil leaves and drizzle with olive oil before serving.',
    ],
  ),
  Recipe(
    id: 'm11',
    title: 'Chicken Parmesan',
    category: 'Main Dish',
    imageUrl: 'assets/images/chicken_parmesan.jpg',
    servingSize: 4,
    cookingTimeMinutes: 35,
    ingredients: const [
      Ingredient(quantity: 4.0, unit: '', name: 'chicken breasts'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'breadcrumbs'),
      Ingredient(quantity: 0.5, unit: 'cup', name: 'grated Parmesan cheese'),
      Ingredient(quantity: 2.0, unit: 'cups', name: 'marinara sauce'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'shredded mozzarella cheese'),
      Ingredient(quantity: 2.0, unit: '', name: 'eggs, beaten'),
    ],
    instructions: [
      'Preheat oven to 400°F.',
      'Mix breadcrumbs and Parmesan cheese in a bowl.',
      'Dip chicken breasts in beaten eggs, then coat with breadcrumb mixture.',
      'Place chicken in a baking dish, top with marinara sauce and mozzarella cheese.',
      'Bake for 25-30 minutes until chicken is cooked through and cheese is melted.',
    ],
  ),
  Recipe(
    id: 'm12',
    title: 'Vegetable Lasagna',
    category: 'Main Dish',
    imageUrl: 'assets/images/vegetable_lasagna.jpg',
    servingSize: 8,
    cookingTimeMinutes: 45,
    ingredients: const [
      Ingredient(quantity: 1.0, unit: 'box', name: 'lasagna noodles'),
      Ingredient(quantity: 2.0, unit: 'cups', name: 'ricotta cheese'),
      Ingredient(quantity: 2.0, unit: 'cups', name: 'shredded mozzarella cheese'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'grated Parmesan cheese'),
      Ingredient(quantity: 2.0, unit: 'jars', name: 'marinara sauce'),
      Ingredient(quantity: 2.0, unit: 'cups', name: 'chopped spinach'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'sliced mushrooms'),
      Ingredient(quantity: 1.0, unit: '', name: 'zucchini, sliced'),
    ],
    instructions: [
      'Preheat oven to 375°F.',
      'Cook lasagna noodles according to package directions.',
      'In a bowl, mix ricotta, spinach, mushrooms, and zucchini.',
      'In a baking dish, layer marinara sauce, noodles, vegetable mixture, and mozzarella cheese.',
      'Repeat layers. Top with Parmesan cheese and bake for 45 minutes.',
      ],
  ),

  Recipe(
    id: 'm13',
    title: 'Pesto Pasta with Cherry Tomatoes',
    category: 'Main Dish',
    imageUrl: 'assets/images/pesto_pasta.jpg',
    servingSize: 4,
    cookingTimeMinutes: 15,
    ingredients: const [
      Ingredient(quantity: 8.0, unit: 'oz', name: 'pasta of choice'),
      Ingredient(quantity: 0.5, unit: 'cup', name: 'basil pesto'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'cherry tomatoes, halved'),
      Ingredient(quantity: 0.25, unit: 'cup', name: 'grated Parmesan cheese'),
    ],
    instructions: [
      'Cook pasta according to package directions.',
      'Drain pasta and return to pot.',
      'Stir in basil pesto and cherry tomatoes.',
      'Sprinkle with Parmesan cheese before serving.',
    ],
  ),
  Recipe(
    id: 'm14',
    title: 'BBQ Pulled Pork Sandwiches',
    category: 'Main Dish',
    imageUrl: 'assets/images/pulled_pork.jpg',
    servingSize: 6,
    cookingTimeMinutes: 480,
    ingredients: const [
      Ingredient(quantity: 3.0, unit: 'lbs', name: 'pork shoulder'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'BBQ sauce'),
      Ingredient(quantity: 6.0, unit: '', name: 'sandwich buns'),
      Ingredient(quantity: 0.0, unit: '', name: 'Coleslaw for topping (optional)'),
    ],
    instructions: [
      'Slow cook pork shoulder in a crockpot for 8 hours on low.',
      'Shred pork with two forks and mix in BBQ sauce.',
      'Serve on sandwich buns with coleslaw if desired.',
    ],
  ),
  Recipe(
    id: 'm15',
    title: 'Thai Green Curry',
    category: 'Main Dish',
    imageUrl: 'assets/images/thai_green_curry.jpg',
    servingSize: 4,
    cookingTimeMinutes: 20,
    ingredients: const [
      Ingredient(quantity: 1.0, unit: 'lb', name: 'chicken thighs, sliced'),
      Ingredient(quantity: 2.0, unit: 'cups', name: 'coconut milk'),
      Ingredient(quantity: 2.0, unit: 'tbsp', name: 'green curry paste'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'bamboo shoots'),
      Ingredient(quantity: 1.0, unit: '', name: 'red bell pepper, sliced'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'Thai basil leaves'),
    ],
    instructions: [
      'In a pot, heat coconut milk and stir in green curry paste.',
      'Add chicken and cook until no longer pink.',
      'Stir in bamboo shoots and bell pepper, simmer for 10 minutes.',
      'Garnish with Thai basil leaves before serving with rice.',
    ],
  ),

  
  Recipe(
    id: 'm30', 
    title: 'Beef Tacos', 
    category: 'Main Dish', 
    imageUrl: 'assets/images/beef_tacos.jpg', 
    servingSize: 6, 
    cookingTimeMinutes: 20,
    ingredients: const [
        Ingredient(quantity: 1.0, unit: 'lb', name: 'Ground Beef'),
        Ingredient(quantity: 12.0, unit: '', name: 'Taco Shells'),
        Ingredient(quantity: 0.0, unit: '', name: 'Lettuce'),
        Ingredient(quantity: 0.0, unit: '', name: 'Cheese'),
    ], 
    instructions: ['Cook beef', 'Assemble tacos with toppings']
  ),

  // --- Desserts (Tatlılar) --- (D1 - D22)
  Recipe(
    id: 'd1',
    title: 'Chocolate Lava Cake',
    category: 'Dessert',
    imageUrl: 'assets/images/lava_cake.jpg',
    servingSize: 2,
    cookingTimeMinutes: 15,
    ingredients: const [
      Ingredient(quantity: 4.0, unit: 'oz', name: 'bittersweet chocolate'),
      Ingredient(quantity: 2.0, unit: 'tbsp', name: 'butter'),
      Ingredient(quantity: 1.0, unit: '', name: 'egg'),
      Ingredient(quantity: 1.0, unit: '', name: 'egg yolk'),
      Ingredient(quantity: 1.0, unit: 'tbsp', name: 'flour'),
      Ingredient(quantity: 2.0, unit: 'tbsp', name: 'sugar'),
    ],
    instructions: [
      'Preheat oven to 425°F. Grease and flour two ramekins.',
      'Melt chocolate and butter together.',
      'Whisk egg, yolk, and sugar until pale.',
      'Fold in chocolate mixture and flour.',
      'Divide batter into ramekins and bake for 12-14 minutes.',
    ],
  ),
  Recipe(
    id: 'd2',
    title: 'Classic Apple Pie',
    category: 'Dessert',
    imageUrl: 'assets/images/apple_pie.jpg',
    servingSize: 8,
    cookingTimeMinutes: 55,
    ingredients: const [
      Ingredient(quantity: 1.0, unit: '', name: 'pie crust package'),
      Ingredient(quantity: 6.0, unit: 'medium', name: 'apples, sliced'),
      Ingredient(quantity: 0.5, unit: 'cup', name: 'sugar'),
      Ingredient(quantity: 1.0, unit: 'tsp', name: 'cinnamon'),
      Ingredient(quantity: 2.0, unit: 'tbsp', name: 'flour'),
      Ingredient(quantity: 1.0, unit: 'tbsp', name: 'butter'),
    ],
    instructions: [
      'Mix apples, sugar, cinnamon, and flour in a large bowl.',
      'Line pie dish with one crust. Fill with apple mixture.',
      'Dot with butter and top with second crust. Seal edges.',
      'Bake at 425°F for 15 minutes, then reduce to 375°F for 35-40 minutes.',
    ],
  ),
  Recipe(
    id: 'd3',
    title: 'Vanilla Cupcakes',
    category: 'Dessert',
    imageUrl: 'assets/images/cupcakes.jpg',
    servingSize: 12,
    cookingTimeMinutes: 25,
    ingredients: const [
      Ingredient(quantity: 1.5, unit: 'cups', name: 'flour'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'sugar'),
      Ingredient(quantity: 0.5, unit: 'cup', name: 'butter'),
      Ingredient(quantity: 2.0, unit: '', name: 'eggs'),
      Ingredient(quantity: 0.5, unit: 'cup', name: 'milk'),
      Ingredient(quantity: 1.0, unit: 'tsp', name: 'vanilla extract'),
      Ingredient(quantity: 1.75, unit: 'tsp', name: 'baking powder'),
    ],
    instructions: [
      'Preheat oven to 350°F and line cupcake tin with liners.',
      'Cream butter and sugar until light and fluffy.',
      'Add eggs one at a time, then stir in vanilla.',
      'Combine flour and baking powder, add to creamed mixture alternately with milk.',
      'Fill liners 2/3 full and bake for 20-25 minutes.',
    ],
  ),
  Recipe(
    id: 'd4',
    title: 'Lemon Bars',
    category: 'Dessert',
    imageUrl: 'assets/images/lemon_bars.jpg',
    servingSize: 9,
    cookingTimeMinutes: 35,
    ingredients: const [
      Ingredient(quantity: 1.0, unit: 'cup', name: 'flour'),
      Ingredient(quantity: 0.25, unit: 'cup', name: 'powdered sugar'),
      Ingredient(quantity: 0.5, unit: 'cup', name: 'butter'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'sugar'),
      Ingredient(quantity: 2.0, unit: '', name: 'eggs'),
      Ingredient(quantity: 0.25, unit: 'cup', name: 'lemon juice'),
      Ingredient(quantity: 2.0, unit: 'tbsp', name: 'flour'),
    ],
    instructions: [
      'Preheat oven to 350°F. Mix 1 cup flour and powdered sugar.',
      'Cut in butter until mixture resembles coarse crumbs. Press into baking dish.',
      'Bake crust for 15-20 minutes until golden.',
      'Whisk together sugar, eggs, lemon juice, and 2 tbsp flour. Pour over crust.',
      'Bake for an additional 20 minutes. Cool and dust with powdered sugar before serving.',
    ],
  ),
  Recipe(
    id: 'd5',
    title: 'Cheesecake',
    category: 'Dessert',
    imageUrl: 'assets/images/cheesecake.jpg',
    servingSize: 12,
    cookingTimeMinutes: 60,
    ingredients: const [
      Ingredient(quantity: 1.5, unit: 'cups', name: 'graham cracker crumbs'),
      Ingredient(quantity: 0.25, unit: 'cup', name: 'melted butter'),
      Ingredient(quantity: 4.0, unit: 'packages (8 oz each)', name: 'cream cheese, softened'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'sugar'),
      Ingredient(quantity: 1.0, unit: 'tsp', name: 'vanilla extract'),
      Ingredient(quantity: 4.0, unit: '', name: 'eggs'),
    ],
    instructions: [
      'Preheat oven to 325°F. Mix graham cracker crumbs and melted butter. Press into springform pan.',
      'Beat cream cheese, sugar, and vanilla until smooth.',
      'Add eggs one at a time, mixing well after each addition.',
      'Pour filling over crust and bake for 55-60 minutes.',
      'Cool and refrigerate for at least 4 hours before serving.',
    ],
  ),
  Recipe(
    id: 'd6',
    title: 'Banana Bread',
    category: 'Dessert',
    imageUrl: 'assets/images/banana_bread.jpg',
    servingSize: 8,
    cookingTimeMinutes: 60,
    ingredients: const [
      Ingredient(quantity: 2.5, unit: '', name: 'ripe bananas, mashed'),
      Ingredient(quantity: 0.33, unit: 'cup', name: 'melted butter'),
      Ingredient(quantity: 0.75, unit: 'cup', name: 'sugar'),
      Ingredient(quantity: 1.0, unit: '', name: 'egg, beaten'),
      Ingredient(quantity: 1.0, unit: 'tsp', name: 'vanilla extract'),
      Ingredient(quantity: 1.0, unit: 'tsp', name: 'baking soda'),
      Ingredient(quantity: 1.5, unit: 'cups', name: 'flour'),
    ],
    instructions: [
      'Preheat oven to 350°F. Grease a loaf pan.',
      'Mix mashed bananas and melted butter.',
      'Stir in sugar, egg, and vanilla.',
      'Add baking soda and flour, mix until just combined.',
      'Pour batter into loaf pan and bake for 60 minutes.',
    ],
  ),
  Recipe(
    id: 'd7',
    title: 'Tiramisu',
    category: 'Dessert',
    imageUrl: 'assets/images/tiramisu.jpg',
    servingSize: 6,
    cookingTimeMinutes: 0,
    ingredients: const [
      Ingredient(quantity: 6.0, unit: '', name: 'egg yolks'),
      Ingredient(quantity: 0.75, unit: 'cup', name: 'sugar'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'mascarpone cheese'),
      Ingredient(quantity: 1.5, unit: 'cups', name: 'heavy cream'),
      Ingredient(quantity: 2.0, unit: 'cups', name: 'brewed espresso, cooled'),
      Ingredient(quantity: 24.0, unit: '', name: 'ladyfinger cookies'),
      Ingredient(quantity: 0.0, unit: '', name: 'Cocoa powder for dusting'),
    ],
    instructions: [
      'Beat egg yolks and sugar until thick and pale.',
      'Fold in mascarpone cheese until smooth.',
      'In a separate bowl, whip heavy cream to stiff peaks and fold into mascarpone mixture.',
      'Dip ladyfingers in espresso and layer in a dish.',
      'Spread half of the mascarpone mixture over ladyfingers. Repeat layers.',
      'Dust with cocoa powder and refrigerate for at least 4 hours before serving.',
    ],
  ),
  Recipe(
    id: 'd8',
    title: 'Chocolate Chip Cookies',
    category: 'Dessert',
    imageUrl: 'assets/images/chocolate_chip_cookies.jpg',
    servingSize: 24,
    cookingTimeMinutes: 12,
    ingredients: const [
      Ingredient(quantity: 1.0, unit: 'cup', name: 'butter, softened'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'sugar'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'brown sugar'),
      Ingredient(quantity: 2.0, unit: '', name: 'eggs'),
      Ingredient(quantity: 2.0, unit: 'tsp', name: 'vanilla extract'),
      Ingredient(quantity: 3.0, unit: 'cups', name: 'flour'),
      Ingredient(quantity: 1.0, unit: 'tsp', name: 'baking soda'),
      Ingredient(quantity: 0.5, unit: 'tsp', name: 'salt'),
      Ingredient(quantity: 2.0, unit: 'cups', name: 'chocolate chips'),
    ],
    instructions: [
      'Preheat oven to 350°F. Line baking sheets with parchment paper.',
      'Cream together butter, sugar, and brown sugar until fluffy.',
      'Add eggs and vanilla, mix well.',
      'Combine flour and baking soda, and salt; gradually add to creamed mixture.',
      'Stir in chocolate chips.',
      'Drop by rounded spoonfuls onto prepared baking sheets and bake for 10-12 minutes.',
    ],
  ),
  Recipe(
    id: 'd9',
    title: 'Strawberry Shortcake',
    category: 'Dessert',
    imageUrl: 'assets/images/strawberry_shortcake.jpg',
    servingSize: 6,
    cookingTimeMinutes: 15,
    ingredients: const [
      Ingredient(quantity: 2.0, unit: 'cups', name: 'sliced strawberries'),
      Ingredient(quantity: 0.25, unit: 'cup', name: 'sugar'),
      Ingredient(quantity: 2.0, unit: 'cups', name: 'all-purpose flour'),
      Ingredient(quantity: 1.0, unit: 'tbsp', name: 'baking powder'),
      Ingredient(quantity: 0.5, unit: 'tsp', name: 'salt'),
      Ingredient(quantity: 0.5, unit: 'cup', name: 'cold butter, cubed'),
      Ingredient(quantity: 0.67, unit: 'cup', name: 'milk'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'heavy cream'),
      Ingredient(quantity: 2.0, unit: 'tbsp', name: 'powdered sugar'),
      Ingredient(quantity: 1.0, unit: 'tsp', name: 'vanilla extract'),
    ],
    instructions: [
      'Toss strawberries with sugar and set aside.',
      'Preheat oven to 425°F. In a bowl, combine flour, baking powder, and salt.',
      'Cut in cold butter until mixture resembles coarse crumbs.',
      'Stir in milk until just combined. Drop dough by spoonfuls onto a baking sheet.',
      'Bake for 12-15 minutes until golden brown.',
      'Whip heavy cream with powdered sugar and vanilla until stiff peaks form.',
      'Split shortcakes, fill with strawberries and whipped cream, and serve.',
    ],
  ),
  Recipe(
    id: 'd10',
    title: 'Pumpkin Pie',
    category: 'Dessert',
    imageUrl: 'assets/images/pumpkin_pie.jpg',
    servingSize: 8,
    cookingTimeMinutes: 55,
    ingredients: const [
      Ingredient(quantity: 1.0, unit: '', name: 'pie crust'),
      Ingredient(quantity: 1.0, unit: 'can (15 oz)', name: 'pumpkin puree'),
      Ingredient(quantity: 1.0, unit: 'can (12 oz)', name: 'evaporated milk'),
      Ingredient(quantity: 0.75, unit: 'cup', name: 'sugar'),
      Ingredient(quantity: 2.0, unit: '', name: 'eggs'),
      Ingredient(quantity: 1.0, unit: 'tsp', name: 'cinnamon'),
      Ingredient(quantity: 0.5, unit: 'tsp', name: 'ginger'),
      Ingredient(quantity: 0.25, unit: 'tsp', name: 'nutmeg'),
      Ingredient(quantity: 0.5, unit: 'tsp', name: 'salt'),
    ],
    instructions: [
      'Preheat oven to 425°F.',
      'In a large bowl, whisk together pumpkin puree, evaporated milk, sugar, eggs, and spices until smooth.',
      'Pour mixture into pie crust.',
      'Bake for 15 minutes, then reduce temperature to 350°F and bake for an additional 40-50 minutes until set.',
      'Cool before serving.',
    ],
  ),
  Recipe(
    id: 'd11',
    title: 'Brownies',
    category: 'Dessert',
    imageUrl: 'assets/images/brownies.jpg',
    servingSize: 16,
    cookingTimeMinutes: 25,
    ingredients: const [
      Ingredient(quantity: 0.5, unit: 'cup', name: 'butter, melted'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'sugar'),
      Ingredient(quantity: 2.0, unit: '', name: 'eggs'),
      Ingredient(quantity: 1.0, unit: 'tsp', name: 'vanilla extract'),
      Ingredient(quantity: 0.33, unit: 'cup', name: 'cocoa powder'),
      Ingredient(quantity: 0.5, unit: 'cup', name: 'flour'),
      Ingredient(quantity: 0.25, unit: 'tsp', name: 'salt'),
      Ingredient(quantity: 0.25, unit: 'tsp', name: 'baking powder'),
    ],
    instructions: [
      'Preheat oven to 350°F. Grease a 9x9 inch baking pan.',
      'In a bowl, mix melted butter, sugar, eggs, and vanilla.',
      'Stir in cocoa powder, flour, salt, and baking powder until just combined.',
      'Pour batter into prepared pan and bake for 20-25 minutes.',
      'Cool before cutting into squares.',
    ],
  ),

  Recipe(
    id: 'd12',
    title: 'Cinnamon Rolls',
    category: 'Dessert',
    imageUrl: 'assets/images/cinnamon_rolls.jpg',
    servingSize: 12,
    cookingTimeMinutes: 30,
    ingredients: const [
      Ingredient(quantity: 4.0, unit: 'cups', name: 'flour'),
      Ingredient(quantity: 0.33, unit: 'cup', name: 'sugar'),
      Ingredient(quantity: 1.0, unit: 'packet', name: 'active dry yeast'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'warm milk'),
      Ingredient(quantity: 0.33, unit: 'cup', name: 'melted butter'),
      Ingredient(quantity: 2.0, unit: '', name: 'eggs'),
      Ingredient(quantity: 1.0, unit: 'tsp', name: 'salt'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'brown sugar'),
      Ingredient(quantity: 2.0, unit: 'tbsp', name: 'cinnamon'),
      Ingredient(quantity: 0.5, unit: 'cup', name: 'butter, softened'),
    ],
    instructions: [
      'In a bowl, combine warm milk, yeast, and sugar. Let sit until frothy.',
      'Add melted butter, eggs, salt, and flour to the yeast mixture. Knead until smooth.',
      'Let dough rise for 1 hour.',
      'Roll out dough into a rectangle. Spread softened butter over dough.',
      'Mix brown sugar and cinnamon, sprinkle over buttered dough.',
      'Roll up dough and cut into 12 rolls. Place in a baking dish and let rise for 30 minutes.',
      'Bake at 350°F for 25-30 minutes until golden brown.',
    ],
  ),
  Recipe(
    id: 'd13',
    title: 'Panna Cotta',
    category: 'Dessert',
    imageUrl: 'assets/images/panna_cotta.jpg',
    servingSize: 4,
    cookingTimeMinutes: 0,
    ingredients: const [
      Ingredient(quantity: 2.0, unit: 'cups', name: 'heavy cream'),
      Ingredient(quantity: 0.5, unit: 'cup', name: 'sugar'),
      Ingredient(quantity: 1.0, unit: 'tsp', name: 'vanilla extract'),
      Ingredient(quantity: 1.0, unit: 'packet', name: 'unflavored gelatin'),
      Ingredient(quantity: 3.0, unit: 'tbsp', name: 'cold water'),
    ],
    instructions: [
      'In a saucepan, heat heavy cream and sugar until sugar dissolves.',
      'Remove from heat and stir in vanilla extract.',
      'In a small bowl, sprinkle gelatin over cold water and let sit for 5 minutes.',
      'Stir gelatin into warm cream mixture until dissolved.',
      'Pour into ramekins and refrigerate for at least 4 hours until set.',
    ],
  ),
  Recipe(
    id: 'd14',
    title: 'Fruit Tart',
    category: 'Dessert',
    imageUrl: 'assets/images/fruit_tart.jpg',
    servingSize: 8,
    cookingTimeMinutes: 15,
    ingredients: const [
      Ingredient(quantity: 1.0, unit: '', name: 'pre-made tart crust'),
      Ingredient(quantity: 1.0, unit: 'cup', name: 'pastry cream'),
      Ingredient(quantity: 2.0, unit: 'cups', name: 'assorted fresh fruit (strawberries, kiwi, blueberries, etc.)'),
      Ingredient(quantity: 0.25, unit: 'cup', name: 'apricot jam'),
    ],
    instructions: [
      'Pre-bake tart crust according to package directions and let cool.',
      'Spread pastry cream evenly in the cooled tart crust.',
      'Arrange fresh fruit on top of the pastry cream.',
      'Heat apricot jam until melted and brush over the fruit for a glossy finish.',
      'Refrigerate for at least 1 hour before serving.',
    ],
  ),

  Recipe(
    id: 'd15',
    title: 'Creme Brulee',
    category: 'Dessert',
    imageUrl: 'assets/images/creme_brulee.jpg',
    servingSize: 4,
    cookingTimeMinutes: 45,
    ingredients: const [
      Ingredient(quantity: 2.0, unit: 'cups', name: 'heavy cream'),
      Ingredient(quantity: 1.0, unit: '', name: 'vanilla bean, split and scraped'),
      Ingredient(quantity: 5.0, unit: '', name: 'egg yolks'),
      Ingredient(quantity: 0.5, unit: 'cup', name: 'sugar'),
      Ingredient(quantity: 0.0, unit: '', name: 'Extra sugar for topping'),
    ],
    instructions: [
      'Preheat oven to 325°F.',
      'In a saucepan, heat heavy cream and vanilla bean until just boiling. Remove from heat and let steep for 15 minutes.',
      'In a bowl, whisk egg yolks and sugar until pale.',
      'Slowly pour warm cream into egg mixture, whisking constantly.',
      'Strain mixture and pour into ramekins. Place ramekins in a baking dish and fill with hot water halfway up the sides.',
      'Bake for 40-45 minutes until set. Chill for at least 2 hours.',
      'Before serving, sprinkle sugar on top and caramelize with a kitchen torch.',
    ],
  ),
  
  
  Recipe(
    id: 'd22', 
    title: 'Key Lime Pie', 
    category: 'Dessert', 
    imageUrl: 'assets/images/key_lime_pie.jpg', 
    servingSize: 6, 
    cookingTimeMinutes: 0,
    ingredients: const [
        Ingredient(quantity: 0.75, unit: 'cup', name: 'Lime Juice'),
        Ingredient(quantity: 14.0, unit: 'oz', name: 'Condensed Milk'),
        Ingredient(quantity: 1.0, unit: '', name: 'Graham Cracker Crust'),
    ], 
    instructions: ['Mix filling', 'Pour into crust', 'Chill for 3 hours']
  ),
  
  
  // SOUPS & SALADS 
 
  
  Recipe(
    id: 's1',
    title: 'Creamy Tomato Soup',
    category: 'Soups & Salads',
    imageUrl: 'assets/images/tomato_soup.jpg',
    servingSize: 4,
    cookingTimeMinutes: 20,
    ingredients: const [
        Ingredient(quantity: 1.0, unit: 'can (28 oz)', name: 'crushed tomatoes'),
        Ingredient(quantity: 1.0, unit: 'cup', name: 'vegetable broth'),
        Ingredient(quantity: 0.5, unit: 'cup', name: 'heavy cream'),
        Ingredient(quantity: 2.0, unit: 'tbsp', name: 'butter'),
        Ingredient(quantity: 1.0, unit: '', name: 'onion, chopped'),
    ],
    instructions: [
        'Sauté onion in butter until soft.',
        'Add crushed tomatoes and vegetable broth. Bring to a simmer.',
        'Stir in heavy cream and heat through (do not boil).',
        'Serve hot, optionally topped with croutons.',
    ],
  ),
  Recipe(
    id: 's2',
    title: 'Classic Caesar Salad',
    category: 'Soups & Salads',
    imageUrl: 'assets/images/caesar_salad.jpg',
    servingSize: 2,
    cookingTimeMinutes: 10,
    ingredients: const [
        Ingredient(quantity: 1.0, unit: 'head', name: 'Romaine lettuce, chopped'),
        Ingredient(quantity: 0.5, unit: 'cup', name: 'Caesar dressing'),
        Ingredient(quantity: 0.5, unit: 'cup', name: 'croutons'),
        Ingredient(quantity: 0.25, unit: 'cup', name: 'Parmesan cheese, shaved'),
    ],
    instructions: [
        'Wash and dry the Romaine lettuce.',
        'Toss lettuce with Caesar dressing.',
        'Top with croutons and shaved Parmesan cheese.',
        'Serve immediately.',
    ],
  ),
  Recipe(
    id: 's3',
    title: 'Broccoli Cheddar Soup',
    category: 'Soups & Salads',
    imageUrl: 'assets/images/broccoli_cheddar_soup.jpg',
    servingSize: 6,
    cookingTimeMinutes: 30,
    ingredients: const [
        Ingredient(quantity: 4.0, unit: 'cups', name: 'broccoli florets'),
        Ingredient(quantity: 2.0, unit: 'cups', name: 'chicken broth'),
        Ingredient(quantity: 2.0, unit: 'cups', name: 'milk'),
        Ingredient(quantity: 1.0, unit: 'cup', name: 'cheddar cheese, shredded'),
        Ingredient(quantity: 0.25, unit: 'cup', name: 'flour'),
        Ingredient(quantity: 0.25, unit: 'cup', name: 'butter'),
    ],
    instructions: [
        'Cook broccoli in broth until tender.',
        'Melt butter in a separate pot, whisk in flour to make a roux.',
        'Gradually whisk in milk until thickened.',
        'Combine milk mixture and broccoli broth. Heat until simmering.',
        'Stir in cheese until melted and smooth.',
    ],
  ),
  Recipe(
    id: 's4',
    title: 'Greek Salad (Horiatiki)',
    category: 'Soups & Salads',
    imageUrl: 'assets/images/greek_salad.jpg',
    servingSize: 4,
    cookingTimeMinutes: 15,
    ingredients: const [
        Ingredient(quantity: 1.0, unit: '', name: 'cucumber, sliced'),
        Ingredient(quantity: 2.0, unit: '', name: 'tomatoes, cut into wedges'),
        Ingredient(quantity: 0.5, unit: '', name: 'red onion, thinly sliced'),
        Ingredient(quantity: 0.5, unit: 'cup', name: 'Kalamata olives'),
        Ingredient(quantity: 4.0, unit: 'oz', name: 'feta cheese block'),
        Ingredient(quantity: 3.0, unit: 'tbsp', name: 'olive oil'),
        Ingredient(quantity: 1.0, unit: 'tbsp', name: 'red wine vinegar'),
    ],
    instructions: [
        'Combine cucumber, tomatoes, and red onion in a bowl.',
        'Add olives. Place the whole feta block on top.',
        'Whisk together olive oil and red wine vinegar.',
        'Drizzle dressing over the salad and serve.',
    ],
  ),
  Recipe(
    id: 's5',
    title: 'French Onion Soup',
    category: 'Soups & Salads',
    imageUrl: 'assets/images/french_onion_soup.jpg',
    servingSize: 4,
    cookingTimeMinutes: 50,
    ingredients: const [
        Ingredient(quantity: 4.0, unit: '', name: 'large onions, sliced'),
        Ingredient(quantity: 4.0, unit: 'cups', name: 'beef broth'),
        Ingredient(quantity: 0.5, unit: 'cup', name: 'dry white wine'),
        Ingredient(quantity: 2.0, unit: 'tbsp', name: 'butter'),
        Ingredient(quantity: 4.0, unit: 'slices', name: 'French bread'),
        Ingredient(quantity: 4.0, unit: 'oz', name: 'Gruyère cheese, shredded'),
    ],
    instructions: [
        'Caramelize sliced onions slowly in butter for 30 minutes.',
        'Deglaze the pan with white wine, then add beef broth.',
        'Simmer for 15 minutes.',
        'Ladle soup into oven-safe bowls. Top with bread slice and Gruyère.',
        'Broil until cheese is melted and bubbly.',
    ],
  ),
  Recipe(
    id: 's6',
    title: 'Caprese Salad',
    category: 'Soups & Salads',
    imageUrl: 'assets/images/caprese_salad.jpg',
    servingSize: 2,
    cookingTimeMinutes: 5,
    ingredients: const [
        Ingredient(quantity: 2.0, unit: '', name: 'large tomatoes, sliced'),
        Ingredient(quantity: 8.0, unit: 'oz', name: 'fresh mozzarella, sliced'),
        Ingredient(quantity: 1.0, unit: 'bunch', name: 'fresh basil leaves'),
        Ingredient(quantity: 2.0, unit: 'tbsp', name: 'olive oil'),
        Ingredient(quantity: 1.0, unit: 'tbsp', name: 'balsamic glaze'),
    ],
    instructions: [
        'Arrange alternating slices of tomato and mozzarella on a plate.',
        'Tuck fresh basil leaves between the slices.',
        'Drizzle with olive oil and balsamic glaze.',
    ],
  ),
  Recipe(
    id: 's7',
    title: 'Lentil Soup ',
    category: 'Soups & Salads',
    imageUrl: 'assets/images/lentil_soup.jpg',
    servingSize: 6,
    cookingTimeMinutes: 40,
    ingredients: const [
        Ingredient(quantity: 1.0, unit: 'cup', name: 'red lentils, rinsed'),
        Ingredient(quantity: 6.0, unit: 'cups', name: 'water or broth'),
        Ingredient(quantity: 1.0, unit: '', name: 'onion, chopped'),
        Ingredient(quantity: 1.0, unit: 'tbsp', name: 'butter'),
        Ingredient(quantity: 1.0, unit: 'tsp', name: 'dried mint'),
        Ingredient(quantity: 0.5, unit: 'tsp', name: 'paprika'),
    ],
    instructions: [
        'Cook lentils, onion, and broth until lentils are very soft.',
        'Blend the soup until smooth.',
        'Melt butter, stir in mint and paprika quickly.',
        'Pour the mint butter over the hot soup before serving.',
    ],
  ),
  Recipe(
    id: 's8',
    title: 'Cobb Salad',
    category: 'Soups & Salads',
    imageUrl: 'assets/images/cobb_salad.jpg',
    servingSize: 2,
    cookingTimeMinutes: 20,
    ingredients: const [
        Ingredient(quantity: 4.0, unit: 'cups', name: 'mixed greens'),
        Ingredient(quantity: 1.0, unit: '', name: 'chicken breast, cooked and diced'),
        Ingredient(quantity: 2.0, unit: '', name: 'hard-boiled eggs, chopped'),
        Ingredient(quantity: 3.0, unit: 'slices', name: 'bacon, cooked and crumbled'),
        Ingredient(quantity: 0.5, unit: 'cup', name: 'blue cheese, crumbled'),
        Ingredient(quantity: 1.0, unit: '', name: 'avocado, diced'),
        Ingredient(quantity: 1.0, unit: 'cup', name: 'dressing of choice'),
    ],
    instructions: [
        'Arrange mixed greens on a large plate.',
        'Line up ingredients (chicken, egg, bacon, cheese, avocado) in rows over the greens.',
        'Drizzle with dressing just before serving.',
    ],
  ),
  Recipe(
    id: 's9',
    title: 'Minestrone Soup',
    category: 'Soups & Salads',
    imageUrl: 'assets/images/minestrone_soup.jpg',
    servingSize: 6,
    cookingTimeMinutes: 45,
    ingredients: const [
        Ingredient(quantity: 4.0, unit: 'cups', name: 'vegetable broth'),
        Ingredient(quantity: 1.0, unit: 'can (14.5 oz)', name: 'diced tomatoes'),
        Ingredient(quantity: 1.0, unit: 'cup', name: 'mixed vegetables (carrots, celery, zucchini)'),
        Ingredient(quantity: 0.5, unit: 'cup', name: 'small pasta (ditalini or shells)'),
        Ingredient(quantity: 0.5, unit: 'cup', name: 'canned beans (kidney or cannellini)'),
    ],
    instructions: [
        'Combine broth, tomatoes, and mixed vegetables in a large pot.',
        'Bring to a boil, then reduce heat and simmer for 20 minutes.',
        'Add pasta and beans. Cook until pasta is tender.',
        'Serve hot, topped with Parmesan cheese if desired.',
    ],
  ),
  Recipe(
    id: 's10',
    title: 'Quinoa Salad with Roasted Vegetables',
    category: 'Soups & Salads',
    imageUrl: 'assets/images/quinoa_salad.jpg',
    servingSize: 4,
    cookingTimeMinutes: 30,
    ingredients: const [
        Ingredient(quantity: 1.0, unit: 'cup', name: 'quinoa, cooked'),
        Ingredient(quantity: 1.0, unit: 'cup', name: 'chopped bell peppers'),
        Ingredient(quantity: 1.0, unit: 'cup', name: 'chopped zucchini'),
        Ingredient(quantity: 0.5, unit: 'cup', name: 'cherry tomatoes'),
        Ingredient(quantity: 2.0, unit: 'tbsp', name: 'olive oil'),
        Ingredient(quantity: 2.0, unit: 'tbsp', name: 'lemon juice'),
    ],
    instructions: [
        'Toss vegetables with olive oil, salt, and pepper. Roast at 400°F for 15 minutes.',
        'Combine cooked quinoa and roasted vegetables in a large bowl.',
        'Dress with lemon juice and serve chilled or warm.',
    ],
  ),
  Recipe(
    id: 's11',
    title: 'Pumpkin Ginger Soup',
    category: 'Soups & Salads',
    imageUrl: 'assets/images/pumpkin_ginger_soup.jpg',
    servingSize: 4,
    cookingTimeMinutes: 30,
    ingredients: const [
        Ingredient(quantity: 1.0, unit: 'can (15 oz)', name: 'pumpkin puree'),
        Ingredient(quantity: 3.0, unit: 'cups', name: 'vegetable broth'),
        Ingredient(quantity: 1.0, unit: 'inch', name: 'fresh ginger, grated'),
        Ingredient(quantity: 0.5, unit: 'cup', name: 'coconut milk'),
        Ingredient(quantity: 1.0, unit: '', name: 'onion, chopped'),
    ],
    instructions: [
        'Sauté onion and ginger until fragrant.',
        'Stir in pumpkin puree and vegetable broth.',
        'Bring to a simmer and cook for 15 minutes.',
        'Stir in coconut milk and blend until smooth.',
        'Serve immediately.',
    ],
  ),
  Recipe(
    id: 's12',
    title: 'Tuna Salad',
    category: 'Soups & Salads',
    imageUrl: 'assets/images/tuna_salad.jpg',
    servingSize: 2,
    cookingTimeMinutes: 5,
    ingredients: const [
        Ingredient(quantity: 1.0, unit: 'can', name: 'tuna, drained'),
        Ingredient(quantity: 0.25, unit: 'cup', name: 'mayonnaise'),
        Ingredient(quantity: 1.0, unit: 'stalk', name: 'celery, finely chopped'),
        Ingredient(quantity: 1.0, unit: 'tsp', name: 'Dijon mustard'),
        Ingredient(quantity: 0.0, unit: '', name: 'Salt and pepper to taste'),
    ],
    instructions: [
        'Flake tuna into a bowl.',
        'Mix in mayonnaise, celery, and Dijon mustard.',
        'Season with salt and pepper.',
        'Serve on lettuce leaves or bread.',
    ],
  ),
  Recipe(
    id: 's13',
    title: 'Gazpacho (Cold Tomato Soup)',
    category: 'Soups & Salads',
    imageUrl: 'assets/images/gazpacho.jpg',
    servingSize: 6,
    cookingTimeMinutes: 20,
    ingredients: const [
        Ingredient(quantity: 4.0, unit: '', name: 'ripe tomatoes'),
        Ingredient(quantity: 1.0, unit: '', name: 'cucumber'),
        Ingredient(quantity: 1.0, unit: '', name: 'red bell pepper'),
        Ingredient(quantity: 0.5, unit: '', name: 'red onion'),
        Ingredient(quantity: 2.0, unit: 'cloves', name: 'garlic'),
        Ingredient(quantity: 0.25, unit: 'cup', name: 'olive oil'),
        Ingredient(quantity: 2.0, unit: 'tbsp', name: 'red wine vinegar'),
    ],
    instructions: [
        'Roughly chop all vegetables and garlic.',
        'Blend vegetables, olive oil, and vinegar until smooth.',
        'Season with salt and pepper.',
        'Chill in the refrigerator for at least 4 hours before serving.',
    ],
  ),
  Recipe(
    id: 's14',
    title: 'Warm Spinach Salad with Bacon Dressing',
    category: 'Soups & Salads',
    imageUrl: 'assets/images/warm_spinach_salad.jpg',
    servingSize: 2,
    cookingTimeMinutes: 15,
    ingredients: const [
        Ingredient(quantity: 4.0, unit: 'cups', name: 'baby spinach'),
        Ingredient(quantity: 4.0, unit: 'slices', name: 'bacon'),
        Ingredient(quantity: 1.0, unit: '', name: 'hard-boiled egg, sliced'),
        Ingredient(quantity: 2.0, unit: 'tbsp', name: 'red wine vinegar'),
        Ingredient(quantity: 1.0, unit: 'tsp', name: 'sugar'),
    ],
    instructions: [
        'Cook bacon until crispy. Remove bacon, reserving the drippings.',
        'Whisk vinegar and sugar into the bacon drippings over low heat.',
        'Place spinach in a bowl. Pour warm dressing over spinach and toss.',
        'Top with crumbled bacon and sliced egg.',
    ],
  ),
  Recipe(
    id: 's15',
    title: 'Chicken Noodle Soup',
    category: 'Soups & Salads',
    imageUrl: 'assets/images/chicken_noodle_soup.jpg',
    servingSize: 8,
    cookingTimeMinutes: 60,
    ingredients: const [
        Ingredient(quantity: 8.0, unit: 'cups', name: 'chicken broth'),
        Ingredient(quantity: 1.0, unit: 'cup', name: 'diced cooked chicken'),
        Ingredient(quantity: 1.0, unit: 'cup', name: 'egg noodles'),
        Ingredient(quantity: 0.5, unit: 'cup', name: 'carrots, sliced'),
        Ingredient(quantity: 0.5, unit: 'cup', name: 'celery, sliced'),
        Ingredient(quantity: 1.0, unit: 'tsp', name: 'dried thyme'),
    ],
    instructions: [
        'Bring chicken broth, carrots, and celery to a boil.',
        'Reduce heat and simmer until vegetables are tender.',
        'Add chicken, noodles, and thyme. Cook until noodles are done.',
        'Season to taste and serve hot.',
    ],
  ),
  Recipe(
    id: 's16',
    title: 'Coleslaw',
    category: 'Soups & Salads',
    imageUrl: 'assets/images/coleslaw.jpg',
    servingSize: 6,
    cookingTimeMinutes: 15,
    ingredients: const [
        Ingredient(quantity: 1.0, unit: 'head', name: 'cabbage, shredded'),
        Ingredient(quantity: 1.0, unit: '', name: 'carrot, grated'),
        Ingredient(quantity: 0.5, unit: 'cup', name: 'mayonnaise'),
        Ingredient(quantity: 2.0, unit: 'tbsp', name: 'apple cider vinegar'),
        Ingredient(quantity: 1.0, unit: 'tbsp', name: 'sugar'),
    ],
    instructions: [
        'Combine shredded cabbage and grated carrot in a large bowl.',
        'In a small bowl, whisk mayonnaise, vinegar, and sugar.',
        'Pour dressing over cabbage mixture and toss well to coat.',
        'Chill for at least 30 minutes before serving.',
    ],
  ),
  Recipe(
    id: 's17',
    title: 'Black Bean Soup',
    category: 'Soups & Salads',
    imageUrl: 'assets/images/black_bean_soup.jpg',
    servingSize: 6,
    cookingTimeMinutes: 40,
    ingredients: const [
        Ingredient(quantity: 2.0, unit: 'cans (15 oz)', name: 'black beans, rinsed'),
        Ingredient(quantity: 4.0, unit: 'cups', name: 'vegetable broth'),
        Ingredient(quantity: 1.0, unit: '', name: 'onion, diced'),
        Ingredient(quantity: 1.0, unit: 'tbsp', name: 'cumin'),
        Ingredient(quantity: 1.0, unit: 'tsp', name: 'chili powder'),
        Ingredient(quantity: 0.0, unit: '', name: 'Optional toppings: sour cream, cilantro'),
    ],
    instructions: [
        'Sauté onion until soft.',
        'Add broth, beans, cumin, and chili powder. Bring to a simmer.',
        'Cook for 20 minutes.',
        'Puree half of the soup for a thicker consistency.',
        'Serve with desired toppings.',
    ],
  ),
  Recipe(
    id: 's18',
    title: 'Watermelon Feta Salad',
    category: 'Soups & Salads',
    imageUrl: 'assets/images/watermelon_feta_salad.jpg',
    servingSize: 4,
    cookingTimeMinutes: 10,
    ingredients: const [
        Ingredient(quantity: 4.0, unit: 'cups', name: 'watermelon, cubed'),
        Ingredient(quantity: 0.5, unit: 'cup', name: 'feta cheese, crumbled'),
        Ingredient(quantity: 0.25, unit: 'cup', name: 'fresh mint, chopped'),
        Ingredient(quantity: 1.0, unit: 'tbsp', name: 'lime juice'),
    ],
    instructions: [
        'Combine cubed watermelon and crumbled feta in a bowl.',
        'Add chopped mint and lime juice.',
        'Gently toss and serve chilled.',
    ],
  ),
  Recipe(
    id: 's19',
    title: 'Potato Leek Soup',
    category: 'Soups & Salads',
    imageUrl: 'assets/images/potato_leek_soup.jpg',
    servingSize: 6,
    cookingTimeMinutes: 45,
    ingredients: const [
        Ingredient(quantity: 4.0, unit: 'medium', name: 'potatoes, peeled and diced'),
        Ingredient(quantity: 2.0, unit: '', name: 'leeks, white and light green parts only, sliced'),
        Ingredient(quantity: 4.0, unit: 'cups', name: 'vegetable broth'),
        Ingredient(quantity: 0.5, unit: 'cup', name: 'heavy cream'),
        Ingredient(quantity: 2.0, unit: 'tbsp', name: 'butter'),
    ],
    instructions: [
        'Sauté leeks in butter until tender.',
        'Add potatoes and broth. Bring to a boil, then simmer until potatoes are soft.',
        'Blend the soup until smooth.',
        'Stir in heavy cream and heat through gently.',
    ],
  ),
  Recipe(
    id: 's20',
    title: 'Arugula Salad with Lemon Vinaigrette',
    category: 'Soups & Salads',
    imageUrl: 'assets/images/arugula_salad.jpg',
    servingSize: 2,
    cookingTimeMinutes: 10,
    ingredients: const [
        Ingredient(quantity: 4.0, unit: 'cups', name: 'arugula'),
        Ingredient(quantity: 0.25, unit: 'cup', name: 'shaved Parmesan'),
        Ingredient(quantity: 2.0, unit: 'tbsp', name: 'pine nuts, toasted'),
        Ingredient(quantity: 3.0, unit: 'tbsp', name: 'olive oil'),
        Ingredient(quantity: 1.0, unit: 'tbsp', name: 'lemon juice'),
    ],
    instructions: [
        'In a small bowl, whisk olive oil, lemon juice, salt, and pepper.',
        'Place arugula in a large bowl.',
        'Drizzle vinaigrette over arugula and toss gently.',
        'Top with Parmesan and pine nuts.',
    ],
  ),
  Recipe(
    id: 's21',
    title: 'Corn Chowder',
    category: 'Soups & Salads',
    imageUrl: 'assets/images/corn_chowder.jpg',
    servingSize: 6,
    cookingTimeMinutes: 40,
    ingredients: const [
        Ingredient(quantity: 3.0, unit: 'cups', name: 'corn (fresh or frozen)'),
        Ingredient(quantity: 2.0, unit: 'cups', name: 'potatoes, diced'),
        Ingredient(quantity: 4.0, unit: 'cups', name: 'chicken broth'),
        Ingredient(quantity: 1.0, unit: 'cup', name: 'heavy cream'),
        Ingredient(quantity: 0.5, unit: '', name: 'onion, diced'),
        Ingredient(quantity: 3.0, unit: 'slices', name: 'bacon, cooked and crumbled'),
    ],
    instructions: [
        'Sauté onion until soft. Add potatoes and broth, cook until potatoes are tender.',
        'Add corn and simmer for 5 minutes.',
        'Stir in heavy cream and heat through.',
        'Serve topped with crumbled bacon.',
    ],
  ),
  Recipe(
    id: 's22',
    title: 'Beet and Goat Cheese Salad',
    category: 'Soups & Salads',
    imageUrl: 'assets/images/beet_goat_cheese_salad.jpg',
    servingSize: 2,
    cookingTimeMinutes: 30,
    ingredients: const [
        Ingredient(quantity: 2.0, unit: 'medium', name: 'beets, roasted and sliced'),
        Ingredient(quantity: 2.0, unit: 'cups', name: 'mixed greens'),
        Ingredient(quantity: 2.0, unit: 'oz', name: 'goat cheese, crumbled'),
        Ingredient(quantity: 0.25, unit: 'cup', name: 'walnuts, toasted'),
        Ingredient(quantity: 2.0, unit: 'tbsp', name: 'balsamic vinaigrette'),
    ],
    instructions: [
        'Combine mixed greens, sliced beets, and walnuts in a bowl.',
        'Crumble goat cheese over the top.',
        'Drizzle with balsamic vinaigrette and serve.',
    ],
  ),
  Recipe(
    id: 's23',
    title: 'Creamy Mushroom Soup',
    category: 'Soups & Salads',
    imageUrl: 'assets/images/creamy_mushroom_soup.jpg',
    servingSize: 4,
    cookingTimeMinutes: 35,
    ingredients: const [
        Ingredient(quantity: 1.0, unit: 'lb', name: 'mushrooms, sliced'),
        Ingredient(quantity: 4.0, unit: 'cups', name: 'vegetable broth'),
        Ingredient(quantity: 0.5, unit: 'cup', name: 'heavy cream'),
        Ingredient(quantity: 2.0, unit: 'tbsp', name: 'butter'),
        Ingredient(quantity: 1.0, unit: '', name: 'shallot, chopped'),
    ],
    instructions: [
        'Sauté shallot in butter until soft.',
        'Add mushrooms and cook until browned.',
        'Pour in broth and simmer for 15 minutes.',
        'Blend the soup until partially smooth (or leave chunky).',
        'Stir in heavy cream and heat gently.',
    ],
  ),
  Recipe(
    id: 's24',
    title: 'Southwestern Quinoa Bowl',
    category: 'Soups & Salads',
    imageUrl: 'assets/images/southwestern_quinoa_bowl.jpg',
    servingSize: 2,
    cookingTimeMinutes: 20,
    ingredients: const [
        Ingredient(quantity: 1.0, unit: 'cup', name: 'quinoa, cooked'),
        Ingredient(quantity: 1.0, unit: 'can (15 oz)', name: 'black beans, rinsed'),
        Ingredient(quantity: 1.0, unit: 'cup', name: 'corn (canned or frozen)'),
        Ingredient(quantity: 1.0, unit: '', name: 'avocado, diced'),
        Ingredient(quantity: 0.5, unit: 'cup', name: 'salsa'),
        Ingredient(quantity: 2.0, unit: 'tbsp', name: 'lime juice'),
    ],
    instructions: [
        'Combine warm quinoa, black beans, and corn.',
        'Top with avocado and salsa.',
        'Drizzle with lime juice and serve.',
    ],
  ),
  Recipe(
    id: 's25',
    title: 'Butternut Squash Soup',
    category: 'Soups & Salads',
    imageUrl: 'assets/images/butternut_squash_soup.jpg',
    servingSize: 6,
    cookingTimeMinutes: 50,
    ingredients: const [
        Ingredient(quantity: 1.0, unit: 'large', name: 'butternut squash, peeled and cubed'),
        Ingredient(quantity: 4.0, unit: 'cups', name: 'vegetable broth'),
        Ingredient(quantity: 1.0, unit: 'tsp', name: 'nutmeg'),
        Ingredient(quantity: 0.5, unit: '', name: 'onion, chopped'),
    ],
    instructions: [
        'Sauté onion until soft.',
        'Add squash and broth. Simmer until squash is tender.',
        'Blend the soup until smooth.',
        'Stir in nutmeg and serve.',
    ],
  ),
  
 
  //  SMOOTHIES & BEVERAGES (15 Tarif)
  
  Recipe(
    id: 'b1',
    title: 'Green Power Smoothie',
    category: 'Smoothies & Beverages',
    imageUrl: 'assets/images/green_smoothie.jpg',
    servingSize: 1,
    cookingTimeMinutes: 5,
    ingredients: const [
        Ingredient(quantity: 1.0, unit: 'cup', name: 'spinach'),
        Ingredient(quantity: 1.0, unit: 'cup', name: 'almond milk'),
        Ingredient(quantity: 0.5, unit: '', name: 'banana, frozen'),
        Ingredient(quantity: 0.5, unit: 'cup', name: 'mango chunks, frozen'),
        Ingredient(quantity: 1.0, unit: 'tsp', name: 'chia seeds'),
    ],
    instructions: [
        'Combine all ingredients in a high-speed blender.',
        'Blend until smooth and creamy.',
        'Add more milk or water if needed to reach desired consistency.',
        'Serve immediately.',
    ],
  ),
  Recipe(
    id: 'b2',
    title: 'Strawberry Banana Smoothie',
    category: 'Smoothies & Beverages',
    imageUrl: 'assets/images/strawberry_banana.jpg',
    servingSize: 1,
    cookingTimeMinutes: 5,
    ingredients: const [
        Ingredient(quantity: 1.0, unit: 'cup', name: 'frozen strawberries'),
        Ingredient(quantity: 1.0, unit: '', name: 'banana'),
        Ingredient(quantity: 0.75, unit: 'cup', name: 'milk (dairy or non-dairy)'),
        Ingredient(quantity: 1.0, unit: 'tbsp', name: 'honey (optional)'),
    ],
    instructions: [
        'Place strawberries, banana, and milk in the blender.',
        'Blend until all chunks are gone and mixture is smooth.',
        'Taste and add honey if desired, blend again quickly.',
        'Pour into a glass and enjoy!',
    ],
  ),
  Recipe(
    id: 'b3',
    title: 'Peanut Butter Protein Shake',
    category: 'Smoothies & Beverages',
    imageUrl: 'assets/images/peanut_butter_protein_shake.jpg',
    servingSize: 1,
    cookingTimeMinutes: 5,
    ingredients: const [
        Ingredient(quantity: 1.0, unit: 'cup', name: 'milk'),
        Ingredient(quantity: 1.0, unit: 'scoop', name: 'protein powder (vanilla or chocolate)'),
        Ingredient(quantity: 2.0, unit: 'tbsp', name: 'peanut butter'),
        Ingredient(quantity: 0.5, unit: '', name: 'banana, frozen'),
    ],
    instructions: [
        'Add milk and protein powder to the blender.',
        'Add peanut butter and frozen banana.',
        'Blend on high speed until completely smooth.',
    ],
  ),
  Recipe(
    id: 'b4',
    title: 'Detox Lemon Ginger Water',
    category: 'Smoothies & Beverages',
    imageUrl: 'assets/images/detox_lemon_ginger_water.jpg',
    servingSize: 4,
    cookingTimeMinutes: 10,
    ingredients: const [
        Ingredient(quantity: 4.0, unit: 'cups', name: 'water'),
        Ingredient(quantity: 1.0, unit: '', name: 'lemon, sliced'),
        Ingredient(quantity: 1.0, unit: 'inch', name: 'ginger, sliced'),
        Ingredient(quantity: 0.5, unit: 'cup', name: 'cucumber, sliced'),
        Ingredient(quantity: 0.25, unit: 'cup', name: 'mint leaves'),
    ],
    instructions: [
        'Combine all ingredients in a large pitcher.',
        'Refrigerate for at least 2 hours to allow flavors to infuse.',
        'Serve chilled.',
    ],
  ),
  Recipe(
    id: 'b5',
    title: 'Mango Lassi',
    category: 'Smoothies & Beverages',
    imageUrl: 'assets/images/mango_lassi.jpg',
    servingSize: 2,
    cookingTimeMinutes: 5,
    ingredients: const [
        Ingredient(quantity: 1.0, unit: 'cup', name: 'mango chunks (fresh or frozen)'),
        Ingredient(quantity: 0.5, unit: 'cup', name: 'plain yogurt'),
        Ingredient(quantity: 0.25, unit: 'cup', name: 'milk'),
        Ingredient(quantity: 1.0, unit: 'tsp', name: 'sugar (optional)'),
        Ingredient(quantity: 0.5, unit: 'tsp', name: 'cardamom powder'),
    ],
    instructions: [
        'Combine mango, yogurt, milk, and sugar (if using) in a blender.',
        'Blend until smooth.',
        'Stir in cardamom powder.',
        'Serve chilled.',
    ],
  ),
  Recipe(
    id: 'b6',
    title: 'Iced Coffee',
    category: 'Smoothies & Beverages',
    imageUrl: 'assets/images/iced_coffee.jpg',
    servingSize: 1,
    cookingTimeMinutes: 5,
    ingredients: const [
        Ingredient(quantity: 1.0, unit: 'cup', name: 'brewed coffee, cooled'),
        Ingredient(quantity: 0.5, unit: 'cup', name: 'milk or cream'),
        Ingredient(quantity: 1.0, unit: 'tbsp', name: 'syrup or sugar (optional)'),
        Ingredient(quantity: 0.0, unit: '', name: 'Ice cubes'),
    ],
    instructions: [
        'Fill a glass with ice cubes.',
        'Pour in cooled coffee.',
        'Add milk/cream and sweetener to taste.',
        'Stir and serve.',
    ],
  ),
  Recipe(
    id: 'b7',
    title: 'Blueberry Oatmeal Smoothie',
    category: 'Smoothies & Beverages',
    imageUrl: 'assets/images/blueberry_oatmeal_smoothie.jpg',
    servingSize: 1,
    cookingTimeMinutes: 5,
    ingredients: const [
        Ingredient(quantity: 0.5, unit: 'cup', name: 'frozen blueberries'),
        Ingredient(quantity: 0.5, unit: 'cup', name: 'milk'),
        Ingredient(quantity: 0.25, unit: 'cup', name: 'rolled oats'),
        Ingredient(quantity: 1.0, unit: 'tbsp', name: 'Greek yogurt'),
        Ingredient(quantity: 1.0, unit: 'tsp', name: 'maple syrup'),
    ],
    instructions: [
        'Combine all ingredients in a blender.',
        'Blend until smooth, scraping down sides if necessary.',
        'Enjoy immediately for a thick, nutritious breakfast.',
    ],
  ),
  Recipe(
    id: 'b8',
    title: 'Hot Chocolate',
    category: 'Smoothies & Beverages',
    imageUrl: 'assets/images/hot_chocolate.jpg',
    servingSize: 1,
    cookingTimeMinutes: 5,
    ingredients: const [
        Ingredient(quantity: 1.0, unit: 'cup', name: 'milk'),
        Ingredient(quantity: 2.0, unit: 'tbsp', name: 'cocoa powder'),
        Ingredient(quantity: 2.0, unit: 'tbsp', name: 'sugar'),
        Ingredient(quantity: 0.25, unit: 'tsp', name: 'vanilla extract'),
    ],
    instructions: [
        'Combine milk, cocoa powder, and sugar in a saucepan.',
        'Heat over medium heat, whisking constantly until steaming (do not boil).',
        'Remove from heat and stir in vanilla extract.',
        'Serve hot, topped with whipped cream or marshmallows.',
    ],
  ),
  Recipe(
    id: 'b9',
    title: 'Pineapple Coconut Water',
    category: 'Smoothies & Beverages',
    imageUrl:  'assets/images/pineapple_coconut_water.jpg',
    servingSize: 2,
    cookingTimeMinutes: 5,
    ingredients: const [
        Ingredient(quantity: 1.0, unit: 'cup', name: 'frozen pineapple chunks'),
        Ingredient(quantity: 1.0, unit: 'cup', name: 'coconut water'),
        Ingredient(quantity: 0.5, unit: '', name: 'lime, juiced'),
    ],
    instructions: [
        'Combine all ingredients in a blender.',
        'Blend until frothy and smooth.',
        'Serve over ice.',
    ],
  ),
  Recipe(
    id: 'b10',
    title: 'Strawberry Lemonade',
    category: 'Smoothies & Beverages',
    imageUrl:  'assets/images/strawberry_lemonade.jpg',
    servingSize: 4,
    cookingTimeMinutes: 10,
    ingredients: const [
        Ingredient(quantity: 1.0, unit: 'cup', name: 'fresh strawberries'),
        Ingredient(quantity: 0.75, unit: 'cup', name: 'lemon juice'),
        Ingredient(quantity: 0.5, unit: 'cup', name: 'sugar'),
        Ingredient(quantity: 3.0, unit: 'cups', name: 'cold water'),
    ],
    instructions: [
        'Muddle strawberries and sugar in a pitcher.',
        'Stir in lemon juice and cold water until sugar dissolves.',
        'Strain if desired, and serve over ice.',
    ],
  ),
  Recipe(
    id: 'b11',
    title: 'Chocolate Banana Smoothie',
    category: 'Smoothies & Beverages',
    imageUrl:  'assets/images/chocolate_banana_smoothie.jpg',
    servingSize: 1,
    cookingTimeMinutes: 5,
    ingredients: const [
        Ingredient(quantity: 1.0, unit: '', name: 'banana, frozen'),
        Ingredient(quantity: 1.0, unit: 'cup', name: 'milk'),
        Ingredient(quantity: 1.0, unit: 'tbsp', name: 'cocoa powder'),
        Ingredient(quantity: 1.0, unit: 'tsp', name: 'honey'),
    ],
    instructions: [
        'Combine all ingredients in a blender.',
        'Blend until creamy and thick.',
        'Serve immediately for a quick treat.',
    ],
  ),
  Recipe(
    id: 'b12',
    title: 'Peach and Ginger Iced Tea',
    category: 'Smoothies & Beverages',
    imageUrl:  'assets/images/peach_ginger_iced_tea.jpg',
    servingSize: 4,
    cookingTimeMinutes: 15,
    ingredients: const [
        Ingredient(quantity: 4.0, unit: 'cups', name: 'brewed black tea, cooled'),
        Ingredient(quantity: 1.0, unit: 'cup', name: 'peach slices (fresh or frozen)'),
        Ingredient(quantity: 0.5, unit: 'inch', name: 'ginger, sliced'),
        Ingredient(quantity: 2.0, unit: 'tbsp', name: 'sugar or syrup'),
    ],
    instructions: [
        'Simmer peach slices, ginger, and sugar with a small amount of water to create a syrup.',
        'Strain the syrup and mix it with the cooled black tea.',
        'Serve chilled over ice.',
    ],
  ),
  Recipe(
    id: 'b13',
    title: 'Mocha Frappuccino',
    category: 'Smoothies & Beverages',
    imageUrl:  'assets/images/mocha_frappuccino.jpg',
    servingSize: 1,
    cookingTimeMinutes: 5,
    ingredients: const [
        Ingredient(quantity: 0.5, unit: 'cup', name: 'cooled coffee'),
        Ingredient(quantity: 0.5, unit: 'cup', name: 'milk'),
        Ingredient(quantity: 2.0, unit: 'tbsp', name: 'chocolate syrup'),
        Ingredient(quantity: 1.0, unit: 'cup', name: 'ice cubes'),
    ],
    instructions: [
        'Combine all ingredients in a blender.',
        'Blend until ice is crushed and drink is smooth and frothy.',
        'Pour into a tall glass and top with whipped cream (optional).',
    ],
  ),
  Recipe(
    id: 'b14',
    title: 'Watermelon Refresher',
    category: 'Smoothies & Beverages',
    imageUrl:  'assets/images/watermelon_refresher.jpg',
    servingSize: 2,
    cookingTimeMinutes: 5,
    ingredients: const [
        Ingredient(quantity: 2.0, unit: 'cups', name: 'watermelon chunks, seeded'),
        Ingredient(quantity: 0.25, unit: 'cup', name: 'lime juice'),
        Ingredient(quantity: 0.25, unit: 'cup', name: 'fresh mint leaves'),
        Ingredient(quantity: 1.0, unit: 'cup', name: 'ice'),
    ],
    instructions: [
        'Combine watermelon, lime juice, and mint leaves in a blender.',
        'Blend until smooth.',
        'Strain the mixture into a glass filled with ice.',
        'Garnish with mint and serve.',
    ],
  ),
  Recipe(
    id: 'b15',
    title: 'Apple Cider Smoothie',
    category: 'Smoothies & Beverages',
    imageUrl: 'assets/images/apple_cider_smoothie.jpg',
    servingSize: 1,
    cookingTimeMinutes: 5,
    ingredients: const [
        Ingredient(quantity: 1.0, unit: 'cup', name: 'apple cider'),
        Ingredient(quantity: 0.5, unit: '', name: 'apple, chopped and frozen'),
        Ingredient(quantity: 0.5, unit: 'tsp', name: 'cinnamon'),
        Ingredient(quantity: 0.5, unit: 'cup', name: 'ice'),
    ],
    instructions: [
        'Combine all ingredients in a blender.',
        'Blend until smooth and thick.',
        'Serve immediately.',
    ],
  ),
];

List<Recipe> getRecipesByCategory(String category) {
  return mockRecipes.where((recipe) => recipe.category == category).toList();
}